export function FocusTasksIcon({ className, size = 48, ...props }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={size}
      height={size}
      viewBox="0 0 64 64"
      fill="none"
      className={className}
      aria-hidden
      {...props}
    >
      {/* === CARD/CLIPBOARD DA LISTA === */}
      {/* fundo sutil que segura todos os itens */}
      <rect
        x="8"
        y="6"
        width="48"
        height="52"
        rx="4"
        fill="currentColor"
        fillOpacity="0.08"
        stroke="currentColor"
        strokeWidth="2"
      />

      {/* clipe no topo do clipboard — detalhe pequeno que reforça "lista de tarefas" */}
      <rect
        x="26"
        y="3"
        width="12"
        height="6"
        rx="1.5"
        fill="currentColor"
        fillOpacity="0.6"
        stroke="currentColor"
        strokeWidth="1.5"
      />

      {/* === ITEM 1 (topo) — primeiro a ser concluído === */}
      <g>
        {/* checkbox — fica filled quando concluído */}
        <rect
          x="13"
          y="14"
          width="6"
          height="6"
          rx="1"
          fill="currentColor"
          fillOpacity="0"
          stroke="currentColor"
          strokeWidth="1.5"
        >
          <animate
            attributeName="fill-opacity"
            values="0;0;0.7;0.7;0"
            keyTimes="0;0.05;0.12;0.92;1"
            dur="6s"
            repeatCount="indefinite"
          />
        </rect>
        {/* check dentro */}
        <path
          d="M14.5 17 L15.7 18.2 L17.5 16"
          stroke="hsl(222 47% 5%)"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="none"
          opacity="0"
        >
          <animate
            attributeName="opacity"
            values="0;0;1;1;0"
            keyTimes="0;0.06;0.12;0.92;1"
            dur="6s"
            repeatCount="indefinite"
          />
        </path>
        {/* texto da tarefa (linha simulando texto) */}
        <line
          x1="22"
          y1="17"
          x2="48"
          y2="17"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          opacity="0.6"
        >
          {/* fade out quando concluído */}
          <animate
            attributeName="opacity"
            values="0.6;0.6;0.3;0.3;0"
            keyTimes="0;0.06;0.12;0.5;0.6"
            dur="6s"
            repeatCount="indefinite"
          />
        </line>
        {/* risco em cima (strikethrough) */}
        <line
          x1="22"
          y1="17"
          x2="22"
          y2="17"
          stroke="currentColor"
          strokeWidth="1.5"
          strokeLinecap="round"
          opacity="0.5"
        >
          <animate
            attributeName="x2"
            values="22;22;48;48;48"
            keyTimes="0;0.06;0.14;0.5;0.6"
            dur="6s"
            repeatCount="indefinite"
          />
          <animate
            attributeName="opacity"
            values="0;0;0.5;0.5;0"
            keyTimes="0;0.06;0.14;0.5;0.6"
            dur="6s"
            repeatCount="indefinite"
          />
        </line>
      </g>

      {/* === ITEM 2 === */}
      <g>
        <rect
          x="13"
          y="24"
          width="6"
          height="6"
          rx="1"
          fill="currentColor"
          fillOpacity="0"
          stroke="currentColor"
          strokeWidth="1.5"
        >
          <animate
            attributeName="fill-opacity"
            values="0;0;0;0.7;0.7;0"
            keyTimes="0;0.12;0.16;0.22;0.92;1"
            dur="6s"
            repeatCount="indefinite"
          />
        </rect>
        <path
          d="M14.5 27 L15.7 28.2 L17.5 26"
          stroke="hsl(222 47% 5%)"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="none"
          opacity="0"
        >
          <animate
            attributeName="opacity"
            values="0;0;0;1;1;0"
            keyTimes="0;0.12;0.16;0.22;0.92;1"
            dur="6s"
            repeatCount="indefinite"
          />
        </path>
        <line
          x1="22"
          y1="27"
          x2="44"
          y2="27"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          opacity="0.6"
        >
          <animate
            attributeName="opacity"
            values="0.6;0.6;0.6;0.3;0.3;0"
            keyTimes="0;0.12;0.16;0.22;0.55;0.65"
            dur="6s"
            repeatCount="indefinite"
          />
        </line>
        <line
          x1="22"
          y1="27"
          x2="22"
          y2="27"
          stroke="currentColor"
          strokeWidth="1.5"
          strokeLinecap="round"
          opacity="0.5"
        >
          <animate
            attributeName="x2"
            values="22;22;22;44;44;44"
            keyTimes="0;0.12;0.16;0.24;0.55;0.65"
            dur="6s"
            repeatCount="indefinite"
          />
          <animate
            attributeName="opacity"
            values="0;0;0;0.5;0.5;0"
            keyTimes="0;0.12;0.16;0.24;0.55;0.65"
            dur="6s"
            repeatCount="indefinite"
          />
        </line>
      </g>

      {/* === ITEM 3 (DESTAQUE — o que importa) === */}
      {/* nunca é concluído. recebe estrela ao final. */}
      <g>
        {/* checkbox fica vazio o tempo todo */}
        <rect
          x="13"
          y="34"
          width="6"
          height="6"
          rx="1"
          fill="currentColor"
          fillOpacity="0"
          stroke="currentColor"
          strokeWidth="1.5"
        />
        {/* texto cresce em opacidade quando os outros somem */}
        <line
          x1="22"
          y1="37"
          x2="46"
          y2="37"
          stroke="currentColor"
          strokeWidth="2.25"
          strokeLinecap="round"
        >
          <animate
            attributeName="opacity"
            values="0.6;0.6;0.6;0.6;0.6;1;1;1"
            keyTimes="0;0.16;0.22;0.3;0.5;0.65;0.92;1"
            dur="6s"
            repeatCount="indefinite"
          />
        </line>
        {/* estrela aparece no canto direito do item-destaque */}
        <g opacity="0">
          <path
            d="M51 33 L52 35.5 L54.5 36 L52.7 37.7 L53.2 40.2 L51 39 L48.8 40.2 L49.3 37.7 L47.5 36 L50 35.5 Z"
            fill="currentColor"
            stroke="currentColor"
            strokeWidth="0.5"
            strokeLinejoin="round"
          />
          <animate
            attributeName="opacity"
            values="0;0;0;0;0;0;1;1;0"
            keyTimes="0;0.2;0.3;0.4;0.5;0.6;0.7;0.92;1"
            dur="6s"
            repeatCount="indefinite"
          />
          <animateTransform
            attributeName="transform"
            type="scale"
            values="0.5;0.5;0.5;0.5;0.5;0.5;1.1;1;1;0.5"
            keyTimes="0;0.2;0.3;0.4;0.5;0.6;0.7;0.78;0.92;1"
            dur="6s"
            repeatCount="indefinite"
            additive="sum"
          />
        </g>
      </g>

      {/* === ITEM 4 === */}
      <g>
        <rect
          x="13"
          y="44"
          width="6"
          height="6"
          rx="1"
          fill="currentColor"
          fillOpacity="0"
          stroke="currentColor"
          strokeWidth="1.5"
        >
          <animate
            attributeName="fill-opacity"
            values="0;0;0;0;0.7;0.7;0"
            keyTimes="0;0.22;0.26;0.3;0.36;0.92;1"
            dur="6s"
            repeatCount="indefinite"
          />
        </rect>
        <path
          d="M14.5 47 L15.7 48.2 L17.5 46"
          stroke="hsl(222 47% 5%)"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="none"
          opacity="0"
        >
          <animate
            attributeName="opacity"
            values="0;0;0;0;1;1;0"
            keyTimes="0;0.22;0.26;0.3;0.36;0.92;1"
            dur="6s"
            repeatCount="indefinite"
          />
        </path>
        <line
          x1="22"
          y1="47"
          x2="49"
          y2="47"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          opacity="0.6"
        >
          <animate
            attributeName="opacity"
            values="0.6;0.6;0.6;0.6;0.3;0.3;0"
            keyTimes="0;0.22;0.26;0.3;0.36;0.6;0.7"
            dur="6s"
            repeatCount="indefinite"
          />
        </line>
        <line
          x1="22"
          y1="47"
          x2="22"
          y2="47"
          stroke="currentColor"
          strokeWidth="1.5"
          strokeLinecap="round"
          opacity="0.5"
        >
          <animate
            attributeName="x2"
            values="22;22;22;22;49;49;49"
            keyTimes="0;0.22;0.26;0.3;0.38;0.6;0.7"
            dur="6s"
            repeatCount="indefinite"
          />
          <animate
            attributeName="opacity"
            values="0;0;0;0;0.5;0.5;0"
            keyTimes="0;0.22;0.26;0.3;0.38;0.6;0.7"
            dur="6s"
            repeatCount="indefinite"
          />
        </line>
      </g>
    </svg>
  )
}
